"""Profile-driven job relevance gate.

Runs at discovery insert time to reject jobs that don't match the user's
profile BEFORE they enter the DB. All filtering derives from profile data —
no hardcoded role names, locations, or seniority thresholds.

Two modes:
1. With LLM-generated relevance_filter (from `applypilot init`) — uses
   role_keywords and anti_keywords generated by LLM from the user's profile.
2. Without — falls back to target_role word matching + location exclusion.

Usage:
    from applypilot.discovery.relevance_gate import is_relevant
    if not is_relevant(title, location, description):
        skip  # don't insert into DB
"""

from __future__ import annotations

import logging
import re
from functools import lru_cache

log = logging.getLogger(__name__)

_YOE_RE = re.compile(
    r"(?:(\d+)\+?\s*(?:years?|yrs?)\s*(?:of\s+)?(?:professional\s+)?(?:experience|exp)"
    r"|(?:minimum|at\s+least|min\.?)\s*(\d+)\s*(?:years?|yrs?)"
    r"|(\d+)\+?\s*(?:years?|yrs?)\s*(?:relevant|hands[- ]on|industry))",
    re.IGNORECASE,
)


@lru_cache(maxsize=1)
def _load_profile_filters() -> dict:
    """Extract filtering criteria from the user's profile. Cached per process."""
    try:
        from applypilot.config import load_resume_json
        resume = load_resume_json()
    except Exception:
        return {}

    meta = resume.get("meta", {}).get("applypilot", {})

    # LLM-generated filter (from init) — preferred
    rf = meta.get("relevance_filter", {})
    role_keywords = set(k.lower() for k in rf.get("role_keywords", []))
    anti_keywords = set(k.lower() for k in rf.get("anti_keywords", []))

    # Fallback: derive from target_role words if no LLM filter
    if not role_keywords:
        target_role = (meta.get("target_role", "") or "").lower()
        role_keywords = {w for w in target_role.split() if len(w) > 2}

    # Location exclusions
    target_locs = meta.get("target_locations", {})
    exclude_countries = [c.lower() for c in target_locs.get("exclude_countries", [])]

    # YOE
    yoe = 0
    try:
        yoe = int(meta.get("years_of_experience_total", 0))
    except (ValueError, TypeError):
        pass

    return {
        "role_keywords": role_keywords,
        "anti_keywords": anti_keywords,
        "exclude_countries": exclude_countries,
        "yoe": yoe,
        "has_llm_filter": bool(rf),
    }


def is_relevant(title: str, location: str = "", description: str = "") -> bool:
    """Profile-driven relevance check. Returns False if job should be skipped.

    Checks (cheapest first):
    1. Anti-keywords — instant reject if title contains one
    2. Location exclusion — reject if in excluded country
    3. Role category — reject if title has zero overlap with role keywords
    4. Seniority — reject if JD requires significantly more YOE than profile
    """
    filters = _load_profile_filters()
    if not filters:
        return True

    title_lower = (title or "").lower()
    location_lower = (location or "").lower()

    # 1. Anti-keywords (LLM-generated blocklist)
    if filters["anti_keywords"] and title_lower:
        if any(ak in title_lower for ak in filters["anti_keywords"]):
            log.debug("[relevance] Anti-keyword reject: %s", title[:40])
            return False

    # 2. Location exclusion
    if filters["exclude_countries"] and location_lower:
        from applypilot.discovery.location_resolver import resolve_country

        country_code = resolve_country(location)
        if country_code:
            # Match against exclude list (supports both codes and names)
            code_lower = country_code.lower()
            for excluded in filters["exclude_countries"]:
                if excluded == code_lower or excluded in location_lower:
                    log.debug("[relevance] Location reject: %s → %s (excludes %s)",
                             title[:40], country_code, excluded)
                    return False

    # 3. Role category
    if filters["role_keywords"] and title_lower:
        if not any(kw in title_lower for kw in filters["role_keywords"]):
            log.debug("[relevance] Role reject: %s", title[:40])
            return False

    # 4. Seniority gate
    if filters["yoe"] and description:
        for m in _YOE_RE.finditer(description[:8000]):
            required = int(next(g for g in m.groups() if g))
            if required > filters["yoe"] + 2:
                log.debug("[relevance] YOE reject: %s needs %d+ (have %d)",
                         title[:40], required, filters["yoe"])
                return False

    return True


def generate_relevance_filter(resume_data: dict) -> dict:
    """LLM-generated relevance filter from profile. Called during `applypilot init`.

    Returns dict to store in meta.applypilot.relevance_filter:
    {
        "role_keywords": ["engineer", "developer", "sde", ...],
        "anti_keywords": ["sales", "marketing", "recruiter", ...]
    }
    """
    from applypilot.llm import get_client
    import json

    meta = resume_data.get("meta", {}).get("applypilot", {})
    target_role = meta.get("target_role", "")
    skills = []
    for sg in resume_data.get("skills", []):
        skills.extend(sg.get("keywords", []))
    work_titles = [w.get("position", "") for w in resume_data.get("work", []) if w.get("position")]

    prompt = f"""Given this job seeker profile, generate two keyword lists for filtering job titles.

Target role: {target_role}
Past titles: {', '.join(work_titles)}
Key skills: {', '.join(skills[:30])}

Return JSON only:
{{
  "role_keywords": ["keyword1", "keyword2", ...],
  "anti_keywords": ["keyword1", "keyword2", ...]
}}

role_keywords: words/phrases that SHOULD appear in relevant job titles. Include synonyms, abbreviations, related roles, seniority prefixes. Be comprehensive — cover all variations job boards use. Include multi-word phrases like "software engineer" and single words like "developer".

anti_keywords: ONLY strong negatives — words that if they are the PRIMARY role (not a modifier) mean the job is definitely irrelevant. Do NOT include words that can be modifiers in valid titles (e.g. "lead", "manager", "senior", "staff", "principal" are modifiers, not roles). Good anti-keywords: "sales", "nurse", "recruiter", "accountant". Bad anti-keywords: "lead", "manager", "analyst" (these appear in valid engineering titles like "Tech Lead", "Engineering Manager", "Data Analyst")."""

    try:
        client = get_client()
        raw = client.chat(
            [{"role": "user", "content": prompt}],
            max_output_tokens=1000,
        )
        start = raw.index("{")
        end = raw.rindex("}") + 1
        result = json.loads(raw[start:end])
        # Normalize to lowercase
        result["role_keywords"] = [k.lower() for k in result.get("role_keywords", [])]
        result["anti_keywords"] = [k.lower() for k in result.get("anti_keywords", [])]
        log.info("[relevance] Generated filter: %d role keywords, %d anti keywords",
                len(result["role_keywords"]), len(result["anti_keywords"]))
        return result
    except Exception as e:
        log.warning("[relevance] LLM filter generation failed: %s", e)
        return {}


def clear_cache() -> None:
    """Clear cached profile filters (call after profile edits)."""
    _load_profile_filters.cache_clear()
