"""Adjacency graph builder — LLM-generated, cached to YAML.

One LLM call generates the full graph from user's skills.
Cached to YAML — never called again unless forced.
"""

from __future__ import annotations

import logging
from pathlib import Path

import yaml

from applypilot.intelligence.adjacency_graph.graph import SkillAdjacencyGraph

log = logging.getLogger(__name__)

_CACHE_PATH = Path(__file__).resolve().parents[2] / "config" / "skill_adjacency.yaml"


def build_graph(
        user_skills: list[str],
        cache_path: Path | None = None,
        force: bool = False,
) -> SkillAdjacencyGraph:
    """Build adjacency graph: load cache or generate via LLM."""
    dest = cache_path or _CACHE_PATH
    graph = SkillAdjacencyGraph()

    if not force and dest.exists():
        count = graph.load_yaml(dest)
        if count > 0:
            graph.enrich_with_user_skills(user_skills)
            return graph

    if not user_skills:
        return graph

    # Generate via LLM
    from applypilot.intelligence.adjacency_graph.providers.llm_provider import generate_adjacencies

    log.info("Generating adjacency graph for %d skills via LLM...", len(user_skills))
    all_edges = generate_adjacencies(user_skills)

    if all_edges:
        yaml_data = {
            "generated": {
                skill: [{"target": t, "confidence": c, "relation": r} for t, c, r in edges]
                for skill, edges in all_edges.items()
            }
        }
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(
            "# Skill Adjacency Graph — auto-generated by LLM\n"
            "# Regenerate: delete this file and run any applypilot command\n\n"
            + yaml.dump(yaml_data, default_flow_style=False, sort_keys=False),
            encoding="utf-8",
        )
        log.info("Cached %d skill adjacencies to %s", len(all_edges), dest)

    graph = SkillAdjacencyGraph()
    graph.load_yaml(dest)
    graph.enrich_with_user_skills(user_skills)
    return graph
