"""Skill adjacency graph (LLD §10).

Layer 0: ESCO API (free, 13K+ skills, all domains)
Layer 1: LLM-generated (niche/new skills)
Layer 2: Cached to YAML (auto-generated by builder.py)

This module is the graph data structure. See builder.py for construction.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from pathlib import Path

import yaml

log = logging.getLogger(__name__)

_DEFAULT_YAML = Path(__file__).resolve().parents[2] / "config" / "skill_adjacency.yaml"


@dataclass(frozen=True)
class AdjacencyEdge:
    source: str
    target: str
    confidence: float
    relation: str


class SkillAdjacencyGraph:
    def __init__(self) -> None:
        self._edges: dict[str, list[AdjacencyEdge]] = {}
        self._reverse: dict[str, list[AdjacencyEdge]] = {}

    def load_yaml(self, path: str | Path | None = None) -> int:
        """Load adjacency edges from YAML. Returns edge count."""
        p = Path(path) if path else _DEFAULT_YAML
        if not p.exists():
            return 0
        data = yaml.safe_load(p.read_text(encoding="utf-8")) or {}
        count = 0
        for _domain, skills in data.items():
            if not isinstance(skills, dict):
                continue
            for source, targets in skills.items():
                src = source.lower()
                for t in targets or []:
                    if not isinstance(t, dict) or "target" not in t:
                        continue
                    edge = AdjacencyEdge(
                        source=src,
                        target=t["target"].lower(),
                        confidence=float(t.get("confidence", 0.5)),
                        relation=t.get("relation", "related"),
                    )
                    self._edges.setdefault(src, []).append(edge)
                    self._reverse.setdefault(edge.target, []).append(edge)
                    count += 1
        return count

    def resolve(self, skill: str, user_skills: set[str]) -> AdjacencyEdge | None:
        """Find best adjacency match between a required skill and user's skills."""
        key = skill.lower()
        if key in user_skills:
            return AdjacencyEdge(source=key, target=key, confidence=1.0, relation="exact")
        for edge in self._edges.get(key, []):
            if edge.target in user_skills:
                return edge
        for edge in self._reverse.get(key, []):
            if edge.source in user_skills:
                return AdjacencyEdge(
                    source=key,
                    target=edge.source,
                    confidence=edge.confidence,
                    relation=edge.relation,
                )
        return None

    def get_edges(self, skill: str) -> list[AdjacencyEdge]:
        return self._edges.get(skill.lower(), [])

    def get_confidence(self, source: str, target: str) -> float:
        """Get adjacency confidence between two skills. Returns 0.0 if no edge."""
        src, tgt = source.lower(), target.lower()
        for edge in self._edges.get(src, []):
            if edge.target == tgt:
                return edge.confidence
        for edge in self._reverse.get(tgt, []):
            if edge.source == src:
                return edge.confidence
        return 0.0

    def enrich_with_user_skills(self, skills: list[str]) -> int:
        """Add self-edges for user's skills so they're always findable."""
        added = 0
        for skill in skills:
            key = skill.lower().strip()
            if key and key not in self._edges:
                edge = AdjacencyEdge(source=key, target=key, confidence=1.0, relation="self")
                self._edges[key] = [edge]
                added += 1
        return added
